chore: Fix style issues
cloudquery/cq-provider-sdk pull request #284
Opened 2022-05-24 12:24 UTC by erezrokah

🎉 Thank you for making CloudQuery awesome by submitting a PR 🎉

#### Summary

Required for https://github.com/cloudquery/cq-provider-sdk/pull/282.
Part of https://github.com/cloudquery/.github/pull/107.
Fixes lint errors based on our new set of rules.

---

Use the following steps to ensure your PR is ready to be reviewed

- [ ] Read the [contribution guidelines](../blob/main/.github/CONTRIBUTING.md) 🧑‍🎓
- [ ] Run `go fmt` to format your code 🖊
- [ ] Lint your changes via `golangci-lint run --new-from-rev main` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [ ] Update or add tests 🧪
- [ ] Ensure the status checks below are successful ✅

2022-05-24 12:26 UTC, erezrokah commented
Actually probably should exclude `cqproto/*`

2022-05-24 13:02 UTC, erezrokah commented on database/postgres/uuid.go
> +func (u UUID) Get() interface{} {
Consistent naming for receiver in the file

2022-05-25 08:50 UTC, disq requested changes
single nit, include cqproto but ignore auto generated code inside

2022-05-25 08:53 UTC, disq approved these changes

2022-05-25 08:56 UTC, disq approved these changes

2022-05-25 08:57 UTC, merged